create table accounts (
                          id bigint generated by default as identity primary key,
                          name varchar(200) not null,
                          balance decimal(19, 2) not null,
                          created_at timestamp not null default current_timestamp
);

create index idx_accounts_name on accounts(name);