create table transfers (
                           id bigint generated by default as identity primary key,
                           from_account_id bigint not null,
                           to_account_id bigint not null,
                           amount decimal(19, 2) not null,
                           created_at timestamp not null default current_timestamp,
                           constraint fk_transfers_from foreign key (from_account_id) references accounts(id),
                           constraint fk_transfers_to foreign key (to_account_id) references accounts(id)
);

create index idx_transfers_from on transfers(from_account_id, created_at);
create index idx_transfers_to on transfers(to_account_id, created_at);

create table account_movements (
                                id bigint generated by default as identity primary key,
                                account_id bigint not null,
                                transfer_id bigint not null,
                                entry_type varchar(10) not null,
                                amount decimal(19, 2) not null,
                                created_at timestamp not null default current_timestamp,
                                constraint fk_movement_account foreign key (account_id) references accounts(id),
                                constraint fk_movement_transfer foreign key (transfer_id) references transfers(id)
);

create index idx_movement_account_created on account_movements(account_id, created_at);